### ISSUE TITLE
Missing nomad/v1/allocation/<id> endpoint

### ISSUE THREAD

**Issue by schlumpfit** [hashicorp/nomad-openapi#106]
Hello,

from what I can see there exists no such endpoint `nomad/v1/allocation/<id>`  in the openapi spec.

On my running instance (v1.2.3) I found the endpoint and it seems to return additional information.

The only way to get my required information was to perform `v1/allocations?resources=true&task_states=true` which produces way more content than necessary and requires additional filtering on the allocation id of interest.

Is there any chance that this endpoint will make it in the openapi spec?

Thanks!

**Comment by DerekStrickland** [comment]
Hi @schlumpfit  

I am sorry you are running into this issue!  It looks like an oversight, and not intentional. I'll take a look at getting that added for you and update this issue.

**Comment by schlumpfit** [comment]
Hi @DerekStrickland,

thanks a lot for your feedback. If there is anything I can help you with, please let me know.
