### ISSUE TITLE
ruby/v1 client seems to be python client

### ISSUE THREAD

**Issue by schlumpfit** [hashicorp/nomad-openapi#78]
The ruby client seems to be a python client due to incorrect config file.
The current [file](https://github.com/hashicorp/nomad-openapi/blob/main/clients/ruby/v1/config.yaml) states:
```
# File is used by the openapi-generator cli to generate a javascript client.
generatorName: python
gitUserId: hashicorp
gitRepoId: nomad-openapi/clients/ruby/v1
inputSpec: /local/v1/openapi.yaml
outputDir: /local/clients/ruby/v1
moduleName: NomadClient
packageVersion: 1.1.4
gemLicense: MPL 2.0
```
But I guess it should be:
```
# File is used by the openapi-generator cli to generate a ruby client.
generatorName: ruby <---
gitUserId: hashicorp
gitRepoId: nomad-openapi/clients/ruby/v1
inputSpec: /local/v1/openapi.yaml
outputDir: /local/clients/ruby/v1
moduleName: NomadClient
packageVersion: 1.1.4
gemLicense: MPL 2.0
```

A bit offtopic:

I am wondering what is the benefit of having all the clients generated in this repository? I think it would make more sense to either publish the generated clients to whatever package manager the language uses or to only keep the configuration files and document the command to generate any of the clients:
```
docker run --rm -v "$PWD:/local" openapitools/openapi-generator-cli:v5.2.0 batch --clean path/to/config.yaml
```

**Comment by DerekStrickland** [comment]
Thank you for raising this issue!  We'll get that fixed as soon as we can. 

Also, thank you for your input on hosting the client output. That is an open question we have for the community, and your input on this topic is welcome and noted.
